{{- if and (eq .Values.persistence.nfs.enabled true) (eq .Values.persistence.enabled true) }}
#NB when mounting this NFS PV, always use a subpath equals to claim name (and containing fullname)
# eg subPath: {{ template "getmesh.fullname" . }}-uploads
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "getmesh.fullname" . }}-uploads
  labels:
    app: {{ template "getmesh.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: {{ .Values.persistence.nfs.storage }}

{{- else if .Values.persistence.enabled }}
#create a regular volume (like getmesh-data)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "getmesh.fullname" . }}-uploads
  labels:
    app: {{ template "getmesh.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  accessModes:
  {{- range .Values.persistence.accessModes }}
  - {{ . | quote }}
  {{- end }}
  {{- if .Values.persistence.storageClass }}
  {{- if (eq "-" .Values.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  {{- end }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
{{- end }}
